version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'py-ansible'
    working_dir: '/root/'
    tty: true
    volumes:
      - ~/code/:/root/code
      - ~/.ssh:/root/.ssh
    privileged: true